name: Create Release
on:
  push:
    branches:
      - "main"
  schedule:
    - cron: '21 4 * * *' # every day at 4:21

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
